# Generated by Django 4.1.5 on 2023-01-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lecture_text", models.CharField(max_length=150)),
                ("lecture_picture", models.ImageField(upload_to="images_uploaded")),
                ("lecture_video", models.FileField(upload_to="video_uploaded")),
                (
                    "course_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MATERIALS.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="subject_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MATERIALS.subject"
            ),
        ),
    ]
