# Generated by Django 4.1.5 on 2023-02-09 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lecture_text", models.CharField(blank=True, max_length=100000)),
                (
                    "lecture_picture",
                    models.ImageField(blank=True, upload_to="upload_image"),
                ),
                (
                    "lecture_video",
                    models.FileField(
                        blank=True, upload_to="upload_video", verbose_name=""
                    ),
                ),
                (
                    "course_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MATERIALS.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="subject_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MATERIALS.subject"
            ),
        ),
    ]
