# Generated by Django 4.1.5 on 2023-01-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MATERIALS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lecture_text",
            field=models.CharField(max_length=100000),
        ),
    ]
