# Generated by Django 4.1.5 on 2023-01-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MATERIALS", "0002_alter_lesson_lecture_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lecture_picture",
            field=models.ImageField(upload_to="media/images_uploaded"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lecture_video",
            field=models.FileField(upload_to="media/video_uploaded"),
        ),
    ]
