# Generated by Django 4.1.5 on 2023-01-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MATERIALS", "0004_alter_lesson_lecture_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lecture_picture",
            field=models.ImageField(upload_to="upload_image"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lecture_video",
            field=models.FileField(upload_to="upload_video"),
        ),
    ]
