# Generated by Django 4.1.5 on 2023-01-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MATERIALS", "0006_alter_lesson_lecture_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lecture_picture",
            field=models.ImageField(blank=True, upload_to="upload_image"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lecture_text",
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lecture_video",
            field=models.FileField(
                blank=True, upload_to="upload_video", verbose_name=""
            ),
        ),
    ]
