# Generated by Django 4.1.5 on 2023-01-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TESTS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test_error_answers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_error_answer", models.CharField(blank=True, max_length=100000)),
                (
                    "test_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="TESTS.course"
                    ),
                ),
            ],
        ),
    ]
