# Generated by Django 4.1.5 on 2023-01-26 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TESTS", "0002_test_error_answers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test_error_answers",
            name="test_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="TESTS.test"
            ),
        ),
    ]
