# Generated by Django 4.1.6 on 2023-02-15 05:09

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("QUIZ", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="prompt",
            new_name="question_text",
        ),
        migrations.AlterField(
            model_name="multiplechoiceanswer",
            name="choices",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), size=None
            ),
        ),
    ]
