# Generated by Django 4.1.6 on 2023-02-15 10:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("QUIZ", "0004_useranswers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswers",
            name="question_id",
        ),
        migrations.AddField(
            model_name="useranswers",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="QUIZ.question",
            ),
        ),
        migrations.AlterField(
            model_name="useranswers",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 15, 16, 29, 38, 60272)
            ),
        ),
        migrations.AlterField(
            model_name="useranswers",
            name="quiz_hash_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="QUIZ.questionhash",
            ),
        ),
        migrations.AlterField(
            model_name="useranswers",
            name="quiz_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="QUIZ.quiz"
            ),
        ),
    ]
