# Generated by Django 4.1.6 on 2023-02-15 10:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("QUIZ", "0005_remove_useranswers_question_id_useranswers_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswers",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 15, 16, 58, 14, 732585)
            ),
        ),
        migrations.AlterField(
            model_name="useranswers",
            name="user_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
