# Generated by Django 4.1.6 on 2023-02-15 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QUIZ", "0006_alter_useranswers_answer_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_solution",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="useranswers",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 15, 17, 16, 41, 992961)
            ),
        ),
    ]
