# Generated by Django 4.1.6 on 2023-02-16 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QUIZ", "0007_question_question_solution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_img",
            field=models.ImageField(blank=True, null=True, upload_to="upload_image/"),
        ),
        migrations.AlterField(
            model_name="useranswers",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 16, 12, 12, 19, 877689)
            ),
        ),
    ]
