# Generated by Django 4.1.6 on 2023-02-16 06:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("QUIZ", "0008_question_question_img_alter_useranswers_answer_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeTextAnswerKaz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_answer_rus",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "correct_answer_kaz",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("case_sensitive", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FreeTextAnswerRus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_answer_rus",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "correct_answer_kaz",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("case_sensitive", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceAnswerKaz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_answer_rus",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "correct_answer_kaz",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "choices",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=200),
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceAnswerRus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_answer_rus",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "correct_answer_kaz",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "choices",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=200),
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="multiplechoiceanswer",
            name="question",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="hash_name",
            new_name="hash_name_rus",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="question_solution",
            new_name="question_solution_kaz",
        ),
        migrations.RenameField(
            model_name="questionhash",
            old_name="hash_name",
            new_name="hash_name_kaz",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_text",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="name",
        ),
        migrations.AddField(
            model_name="question",
            name="question_solution_rus",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="question_text_kaz",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="question_text_rus",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="questionhash",
            name="hash_name_rus",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="name_kaz",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="name_rus",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="useranswers",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 16, 12, 59, 34, 845502)
            ),
        ),
        migrations.DeleteModel(
            name="FreeTextAnswer",
        ),
        migrations.DeleteModel(
            name="MultipleChoiceAnswer",
        ),
        migrations.AddField(
            model_name="multiplechoiceanswerrus",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="QUIZ.question"
            ),
        ),
        migrations.AddField(
            model_name="multiplechoiceanswerkaz",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="QUIZ.question"
            ),
        ),
        migrations.AddField(
            model_name="freetextanswerrus",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="QUIZ.question"
            ),
        ),
        migrations.AddField(
            model_name="freetextanswerkaz",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="QUIZ.question"
            ),
        ),
    ]
