# Generated by Django 4.1.6 on 2023-02-16 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QUIZ", "0009_freetextanswerkaz_freetextanswerrus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswers",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 16, 14, 31, 40, 22606)
            ),
        ),
    ]
