# Generated by Django 4.1.6 on 2023-02-16 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QUIZ", "0010_alter_useranswers_answer_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionhash",
            name="hash_name_kaz",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="questionhash",
            name="hash_name_rus",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="name_kaz",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="name_rus",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="useranswers",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 16, 14, 35, 20, 617089)
            ),
        ),
    ]
