# Generated by Django 4.1.6 on 2023-02-16 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QUIZ", "0011_alter_questionhash_hash_name_kaz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionhash",
            name="hash_name_kaz",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="questionhash",
            name="hash_name_rus",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="name_kaz",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="name_rus",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="useranswers",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 16, 14, 36, 11, 88085)
            ),
        ),
    ]
