# Generated by Django 4.1.6 on 2023-02-27 03:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("QUIZ", "0012_alter_questionhash_hash_name_kaz_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_rus", models.CharField(blank=True, max_length=100, null=True)),
                ("name_kaz", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="useranswers",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 27, 9, 38, 57, 84641)
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="subject_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="QUIZ.subject",
            ),
        ),
    ]
