# Generated by Django 4.1.6 on 2023-02-27 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QUIZ", "0013_subject_alter_useranswers_answer_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswers",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 27, 10, 0, 20, 900783)
            ),
        ),
    ]
